-- AlterTable
ALTER TABLE "flats" ADD COLUMN     "userId" TEXT NOT NULL DEFAULT '8df1da66-f6e8-4284-8812-bd5fa5356010';

-- AddForeignKey
ALTER TABLE "flats" ADD CONSTRAINT "flats_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
